// Generated by CoffeeScript 1.5.0
(function() {
  'use strict';
  angular.module('realEstateApp').controller('MainCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  }).controller('NotFoundCtrl', function() {});

}).call(this);
