// Generated by CoffeeScript 1.5.0
(function() {

  angular.module('realEstateApp').controller('PropertyCtrl', function($scope, PropertySupplier, $routeParams, $location) {
    var property;
    property = PropertySupplier.find($routeParams.id);
    if (property) {
      return $scope.property = property;
    } else {
      return $location.path('/not_found');
    }
  });

}).call(this);
