// Generated by CoffeeScript 1.5.0
(function() {
  'use strict';
  angular.module('realEstateApp').controller('StockCtrl', function($scope, StockRepository) {
    $scope.stock = {
      symbol: 'N/A',
      LastTradePriceOnly: 'N/A'
    };
    if (StockRepository.search_results) {
      $scope.stock = StockRepository.search_results.quote;
    }
    return console.log($scope.stock);
  });

}).call(this);
